title: МЕТОД — А # Для name_bar
url_title: МЕТОД — А | Решения для бизнеса
email: mail@method-a.ru
phone: +79310037539
telegram: method_a
telegram_dm: merkoeva_work
whatsapp: 79310037539
baseurl: ""
url: https://method-a.ru
serv_ip: 87.120.84.80